
WITH raw_data AS (
    SELECT
        RAW_AUTHOR:AUTHOR_UID::INT AS AUTHOR_UID,
        RAW_AUTHOR:FIRST_NAME::STRING AS FIRST_NAME,
        RAW_AUTHOR:LAST_NAME::STRING AS LAST_NAME,
        RAW_AUTHOR:MIDDLE_NAME::STRING AS MIDDLE_NAME
    FROM LIBRARY_CARD_CATALOG.PUBLIC.AUTHOR_INGEST_JSON
)

SELECT *
FROM raw_data
