version: 2
models:
  - name: format_injested_json
    description: "Model for transforming raw author JSON into structured data"
    tests:
      - unique:
          column_name: AUTHOR_UID
      - not_null:
          column_name: FIRST_NAME
      - not_null:
          column_name: LAST_NAME

  - name: books_data
    description: "Model for seeding books data"
    tests:
      - unique:
          column_name: BOOK_UID
      - not_null:
          column_name: TITLE
      - not_null:
          column_name: AUTHOR_UID

  - name: formated_dates
    description: "Model for seeding books data but with formated dates"
    tests:
      - unique:
          column_name: BOOK_UID
      - not_null:
          column_name: FORMATTED_RELEASE_DATE

  - name: product_summary
    description: "A summary of products by category including count, average price, and total quantity"
    columns:
      - name: category
        description: "The category of the product"
        tests:
          - not_null
      - name: product_count
        description: "The count of products in each category"
        tests:
          - unique
      - name: average_price
        description: "The average price of products in the category"
      - name: total_quantity
        description: "The total quantity of products in the category"