version: 2
models:
  - name: format_injested_json
    description: "Model for transforming raw author JSON into structured data"
    tests:
      - unique:
          column_name: AUTHOR_UID
      - not_null:
          column_name: FIRST_NAME
      - not_null:
          column_name: LAST_NAME

  - name: books_data
    description: "Model for seeding books data"
    tests:
      - unique:
          column_name: BOOK_UID
      - not_null:
          column_name: TITLE
      - not_null:
          column_name: AUTHOR_UID

  - name: formated_dates
    description: "Model for seeding books data but with formated dates"
    tests:
      - unique:
          column_name: BOOK_UID
      - not_null:
          column_name: FORMATTED_RELEASE_DATE